# Generated by Django 2.1.7 on 2019-04-11 17:36

import Sell_it.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=Sell_it.fields.PhoneField(default=380979120963, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
