# Generated by Django 2.1.7 on 2019-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
        ('users', '0003_auto_20190411_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='liked_realty', to='realty.Realty'),
        ),
    ]
