# Generated by Django 2.1.7 on 2019-06-20 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190520_1916'),
        ('users', '0005_auto_20190513_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2019, 6, 21, 16, 33, 8, 604479, tzinfo=utc))),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Realty')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
