# Generated by Django 2.1.7 on 2019-04-22 13:29

import Sell_it.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('₴', '₴')], max_length=1)),
                ('area', models.PositiveIntegerField()),
                ('flooring', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('owner_phone', Sell_it.fields.PhoneField(db_index=True, max_length=14, unique=False)),
                ('owner_name', models.CharField(max_length=50)),
                ('offer', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=10)),
                ('type', models.CharField(choices=[('Apt', 'Apartment'), ('Bldg', 'Building')], max_length=15)),
                ('link', models.URLField(blank=True, db_index=True, max_length=2000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealtyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='realty_img')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('realty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realty.Realty')),
                ('floor', models.PositiveIntegerField()),
                ('kitchen_area', models.PositiveIntegerField()),
            ],
            bases=('realty.realty',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('realty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realty.Realty')),
                ('field_area', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            bases=('realty.realty',),
        ),
        migrations.AddField(
            model_name='realtyphoto',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Realty'),
        ),
        migrations.AddField(
            model_name='realty',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
