# Generated by Django 2.1.7 on 2019-04-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='type',
        ),
    ]
