# Generated by Django 2.1.7 on 2019-05-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190501_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='realty',
            name='identity',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='realtyphoto',
            name='realty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='realty.Realty'),
        ),
    ]
